src/Entity/Eleve.php
<?php

namespace App\Entity;

use App\Repository\EleveRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EleveRepository::class)
 */
class Eleve
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nom_complet;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $lieu_naissance;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class)
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity=Tuteur::class)
     */
    private $tuteur;

    /**
     * @ORM\ManyToOne(targetEntity=Etat::class)
     */
    private $etat;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomComplet(): ?string
    {
        return $this->nom_complet;
    }

    public function setNomComplet(string $nom_complet): self
    {
        $this->nom_complet = $nom_complet;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(?string $lieu_naissance): self
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getTuteur(): ?Tuteur
    {
        return $this->tuteur;
    }

    public function setTuteur(?Tuteur $tuteur): self
    {
        $this->tuteur = $tuteur;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/EleveController.php
<?php

namespace App\Controller;

use App\Entity\AnneeScolaire;
use App\Entity\Categorie;
use App\Entity\Classe;
use App\Entity\Eleve;
use App\Entity\Etat;
use App\Entity\Inscription;
use App\Entity\Tuteur;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\Types\True_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;

class EleveController extends AbstractController
{
    /**
     * @Route("/eleve/id", name="eleve")
     */
    public function index(): Response
    {
        return $this->render('eleve/index.html.twig', [
            'controller_name' => 'EleveController',
        ]);
    }

    /**
     * @Route("/affectation_eleve/{id}", name="affectation_eleve")
     */
    public function affecter_eleve($id, EntityManagerInterface $entityManager, Request $request)
    {
        $eleve = $this->getDoctrine()->getRepository(Inscription::class)
            ->findOneBy(['token'=>$id]);
        if($request->isMethod('post'))
        {
            $data = $request->request->all();
            if($this->isCsrfTokenValid('affectation', $data['_token']))
            {
                $classe = $this->getDoctrine()->getRepository(Classe::class)
                    ->find($data['classe']);
                $eleve->setClasse($classe);
                $entityManager->persist($eleve);
                $entityManager->flush();
            }
        }
        $classes = $this->getDoctrine()->getRepository(Classe::class)
            ->findAll();
        $etats = $this->getDoctrine()->getRepository(Etat::class)
            ->findAll();

        return $this->render('eleve/affectation.html.twig', [
            'eleve'=>$eleve,
            'classes'=>$classes,
            'etats'=>$etats
        ]);
    }

    /**
     * @Route("/changer_etat", name="changer_etat")
     */
    public function changer_etat(EntityManagerInterface $entityManager, Request $request)
    {
        if($request->isMethod('POST'))
        {
            $data = $request->request->all();
            //dd($data);
            if($this->isCsrfTokenValid('etat', $data['_token']))
            {
                $eleve = $this->getDoctrine()->getRepository(Eleve::class)
                    ->find($data['eleve']);
                $inscription = $this->getDoctrine()->getRepository(Inscription::class)
                    ->findOneBy(['eleve'=>$eleve]);
                $etat = $this->getDoctrine()->getRepository(Etat::class)
                    ->find($data['etat']);
                $eleve->setEtat($etat);
                $entityManager->persist($eleve);
                //dd($inscription);
                $entityManager->flush();
                return $this->redirectToRoute('affectation_eleve', ['id'=> $inscription->getId()]);
            }
        }
    }

    /**
     * @Route("eleves_non_actifs", name="eleves_non_actifs")
     */
    public function eleves_non_actifs()
    {
        $inscriptions = $this->getDoctrine()->getRepository(Inscription::class)
            ->findElevesNonActifs();
        return $this->render('/eleve/eleves_non_actifs.html.twig', [
            'inscriptions'=>$inscriptions
        ]);
    }

    /**
     * @Route("eleves_disponibles", name="eleves_disponibles")
     */
    public function eleves_disponibles()
    {
        $eleves = $this->getDoctrine()->getRepository(Eleve::class)
            ->findAll();
        return $this->render('eleve/eleves_disponibles.html.twig', [
            'eleves'=>$eleves
        ]);
    }

    /**
     * @Route("profil_eleve/{id}", name="profil_eleve")
     */
    public function profil_eleve($id, Request $request, EntityManagerInterface $entityManager)
    {
        $session = new Session();
        $eleve = $this->getDoctrine()->getRepository(Eleve::class)
            ->find($id);
        $tuteurs = $this->getDoctrine()->getRepository(Tuteur::class)
            ->findAll();
        $etats = $this->getDoctrine()->getRepository(Etat::class)
            ->findBy(['is_active'=>true], []);
        $categories = $this->getDoctrine()->getRepository(Categorie::class)
            ->findBy(['is_active'=>true], []);
        $classes = $this->getDoctrine()->getRepository(Classe::class)
            ->findBy(['is_active'=> true], []);
        $annee = $this->getDoctrine()->getRepository(AnneeScolaire::class)
            ->find($session->get('id_annee'));
        if($request->isMethod('post')){
            $data = $request->request->all();
            if($this->isCsrfTokenValid('place', $data['_token']))
            {
                $inscription = new Inscription();
                $inscription->setToken($data['_token']);
                $inscription->setAnneeScolaire($annee);
                $inscription->setEleve($eleve);
                $inscription->setCreatedBy($this->getUser());
                $inscription->setClasse($this->getDoctrine()->getRepository(Classe::class)
                    ->find($data['classe']));
                $inscription->setCreatedAt(new \DateTime('now'));
                $entityManager->persist($inscription);
                $entityManager->flush();
            }
        }
        //dd($eleve);
        return $this->render('eleve/profil_eleve.html.twig', [
            'eleve'=>$eleve,
            'classes'=>$classes,
            'tuteurs'=>$tuteurs,
            'categories'=>$categories,
            'etats'=>$etats
        ]);
    }

    /**
     * @Route("modifier_eleve", name="modifier_eleve")
     */
    public function modifier_eleve(Request $request,EntityManagerInterface $entityManager)
    {

        if($request->isMethod('post'))
        {

            $data = $request->request->all();
            if($this->isCsrfTokenValid('modifier', $data['_token']))
            {
                $eleve = $this->getDoctrine()->getRepository(Eleve::class)
                    ->find($data['eleve']);
                if($data['date_naissance'] != "")
                {
                    $eleve->setDateNaissance($data['date_naissance']);
                }
                if(isset($data['categorie']) or !empty($data['categorie']) and $data['categorie'] > 0)
                {
                    $eleve->setCategorie($this->getDoctrine()->getRepository(Categorie::class)
                        ->find($data['categorie']));
                }

                if(isset($data['etat']) or !empty($data['etat']) and $data['etat'] > 0)
                {
                    $eleve->setEtat($this->getDoctrine()->getRepository(Etat::class)
                        ->find($data['etat'])
                    );
                }
                if(isset($data['tuteur']) or !empty($data['tuteur']) and $data['tuteur'] > 0)
                {
                    $eleve->setTuteur($this->getDoctrine()->getRepository(Tuteur::class)
                        ->find($data['tuteur'])
                    );
                }
                $eleve->setNomComplet($data['nom_complet']);
                $eleve->setLieuNaissance($data['lieu_naissance']);
                $eleve->setAdresse($data['adresse']);
                $entityManager->persist($eleve);
                $entityManager->flush();
                return $this->redirectToRoute('profil_eleve', ['id'=>$data['eleve']]);
            }
        }
    }
}

templates/eleve/affectation.html.twig
{% include 'extension/sidebar.html.twig' %}
<!-- Header -->
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <h6 class="h2 text-white d-inline-block mb-0">Default</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#">Accueil</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Inscription</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- Card stats -->
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Page </h3>
                        </div>
                        <div class="col text-right">
                            <a href="#!" class="btn btn-sm btn-primary">See all</a>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <form method="post">
                        <div class="row">
                            <div class="col">
                                <select name="classe" id="classe" class="form-control small">
                                    {% for classe in classes %}
                                        <option value="{{ classe.id }}">{{ classe.designation~' '~classe.options.designation }}</option>
                                    {% endfor %}
                                </select>
                                <input type="hidden" name="_token" value="{{ csrf_token('affectation') }}">
                            </div>
                            <div class="col">
                                <input type="submit" class="btn btn-primary" value="AFFECTER">
                            </div>
                        </div>
                    </form>
                    <form action="{{ path('changer_etat') }}" method="POST">
                        <div class="row">
                            <div class="col">
                                <select name="etat" id="etat" class="form-control small">
                                    {% for etat in etats %}
                                        <option value="{{ etat.id }}">{{ etat.designation }}</option>
                                    {% endfor %}
                                </select>
                                <input type="hidden" name="_token" value="{{ csrf_token('etat') }}">
                                <input type="hidden" name="eleve" value="{{ eleve.eleve.id }}">
                            </div>
                            <div class="col">
                                <input type="submit" class="btn btn-primary" value="ENREGISTRER">
                            </div>
                        </div>
                        </form>

                    <div class="row">
                        <div class="col">Nom et postnom: {{ eleve.eleve.nomComplet }}</div>
                        <div class="col">Classe: {{ eleve.classe.designation~' '~eleve.classe.options.designation }}</div>
                        <div class="col">Catégorie: {{ eleve.eleve.categorie.designation }}</div>
                        <div class="col">Etat: {{ eleve.eleve.etat.designation }}</div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include "extension/footer.html.twig" %}
</div>

templates/eleve/eleves_disponibles.html.twig
{% include 'extension/sidebar.html.twig' %}
<!-- Header -->
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <h6 class="h2 text-white d-inline-block mb-0">Default</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#">Accueil</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Inscription</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- Card stats -->
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Eleves non actifs</h3>
                        </div>
                        <div class="col-md-4 text-right">
                            <input type="text" class="form-control my-2" id="myInput" placeholder="Recherche...">
                            {#                            <button onclick="HTMLtoPDF()" class="btn btn-sm btn-primary">See all</button>#}
                        </div>
                    </div>
                </div>
                {#                <div class="container" id="HTMLtoPDF">#}
                <div class="table-responsive" id="HTMLtoPDF">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nom complet</th>
                            <th scope="col">Type</th>
                            <th scope="col">Date Création</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody id="tbody">
                        {% set i = 1 %}
                        {% for eleve in eleves %}
                            <tr>
                                <td>
                                    {{ i }}
                                </td>
                                <td>
                                    {{ eleve.nomComplet|upper }}
                                </td>
                                <td>
                                    {{ eleve.etat.designation }}
                                </td>
                                <td>
                                    {{ eleve.createdAt|date('d-m-Y') }}
                                </td>
                                <td>
                                    <a href="{{ path('profil_eleve', {'id': eleve.id}) }}">Confirmer Place</a>
                                </td>
                            </tr>
                            {% set i = i + 1 %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% include "extension/footer.html.twig" %}
</div>

templates/eleve/eleves_non_actifs.html.twig
{% include 'extension/sidebar.html.twig' %}
<!-- Header -->
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <h6 class="h2 text-white d-inline-block mb-0">Default</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#">Accueil</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Inscription</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- Card stats -->
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Eleves non actifs</h3>
                        </div>
                        <div class="col-md-4 text-right">
                            <input type="text" class="form-control my-2" id="myInput" placeholder="Recherche...">
{#                            <button onclick="HTMLtoPDF()" class="btn btn-sm btn-primary">See all</button>#}
                        </div>
                    </div>
                </div>
{#                <div class="container" id="HTMLtoPDF">#}
                    <div class="table-responsive" id="HTMLtoPDF">
                        <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nom complet</th>
                            <th scope="col">Classe</th>
                            <th scope="col">Type</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody id="tbody">
                        {% set i = 1 %}
                        {% for inscription in inscriptions %}
                            <tr>
                                <td>
                                    {{ i }}
                                </td>
                                <td>
                                    {{ inscription.eleve.nomComplet|upper }}
                                </td>
                                <td>
                                    {{ inscription.classe.designation ~' '~inscription.classe.options.designation }}
                                </td>
                                <td>
                                    {{ inscription.eleve.etat.designation }}
                                </td>
                                <td>
                                    <a href="{{ path('paiement', {'inscription':inscription.id}) }}">Payer</a>
                                    <a href="{{ path('affectation_eleve', {'id': inscription.id}) }}">Affecter</a>
                                </td>
                            </tr>
                            {% set i = i + 1 %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% include "extension/footer.html.twig" %}
</div>

templates/eleve/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EleveController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Bigga/schoolapp/src/Controller/EleveController.php'|file_link(0) }}">src/Controller/EleveController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Bigga/schoolapp/templates/eleve/index.html.twig'|file_link(0) }}">templates/eleve/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/eleve/profil_eleve.html.twig
{% include 'extension/sidebar.html.twig' %}
<!-- Header -->
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <h6 class="h2 text-white d-inline-block mb-0">Default</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#">Accueil</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Inscription</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- Card stats -->
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Profil Elève</h3>
                        </div>
                        <div class="col-md-4 text-right">
                            <span id="modifier" class="btn btn-primary">Modifier les Informations</span>
                            {#                            <button onclick="HTMLtoPDF()" class="btn btn-sm btn-primary">See all</button>#}
                        </div>
                    </div>
                </div>
                {#                <div class="container" id="HTMLtoPDF">#}
                <div class="table-responsive" id="HTMLtoPDF">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <span>Nom: {{ eleve.nomComplet }}</span>
                            </div>
                            <div class="col">
                                <span>Lieu et Date Naissance: {{ eleve.lieuNaissance ~' '~eleve.dateNaissance|date('d/m/Y') }}</span>
                            </div>
                            <div class="col">
                                <span>Adresse : {{ eleve.adresse }}</span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <span>Tuteur : {{ eleve.tuteur.nomComplet }}</span>
                            </div>
                            <div class="col">
                                <span>Categorie : {{ eleve.categorie.designation }}</span>
                            </div>
                            <div class="col">
                                <span>Etat: {{ eleve.etat.designation }}</span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <form method="post">
                                    <h3>Confirmer la Place</h3>
                                    <div class="form-group">
                                        <select name="classe" class="form-control" id="classe">
                                            <option value="-1" hidden selected disabled>Choisir la classe</option>
                                            {% for classe in classes %}
                                                <option value="{{ classe.id }}">{{ classe.designation~' '~classe.options.designation }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <input type="hidden" value="{{ csrf_token('place') }}" name="_token">
                                        <input type="submit" class="btn btn-primary" value="Confirmer Place">
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="row" id="form_modifier">
                            <div class="col">
                                <form method="post" action="{{ path('modifier_eleve') }}">
                                    <div class="form-group">
                                        <input type="text" name="nom_complet" value="{{ eleve.nomComplet }}" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="adresse" value="{{ eleve.adresse }}">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="lieu_naissance" value="{{ eleve.lieuNaissance }}">
                                    </div>
                                    <div class="form-group">
                                        <input type="date" name="date_naissance" class="form-control" value="{{ eleve.dateNaissance|date('d/m/Y') }}">
                                        <input type="hidden" value="{{ csrf_token('modifier') }}" name="_token">
                                        <input type="hidden" value="{{ eleve.id }}" name="eleve">
                                    </div>
                                    <div class="form-group"></div>

                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <select name="tuteur" id="tuteur" class="form-control">
                                        <option value="-1" selected hidden disabled>changer le tuteur</option>
                                        {% for tuteur in tuteurs %}
                                            <option value="{{ tuteur.id }}">{{ tuteur.nomComplet }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <select name="categorie" id="categorie" class="form-control">
                                        <option value="-1" selected hidden disabled>Modifier l'état</option>
                                        {% for categorie in categories %}
                                            <option value="{{ categorie.id }}">{{ categorie.designation }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <select name="etat" id="etat" class="form-control">
                                        <option value="-1" selected hidden disabled>Modifier le tuteur</option>
                                        {% for etat in etats %}
                                            <option value="{{ etat.id }}">{{ etat.designation }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <a href="" class="btn btn-danger">Annuler</a>
                                    <input type="submit" class="btn btn-primary" value="ENREGISTRER">
                                </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include "extension/footer.html.twig" %}
</div>
<script>
    $(document).ready(function(){
        $("#form_modifier").hide()
        $("#modifier").on('click', function(){
            $("#form_modifier").show()
        })
    })
</script>