src/Entity/Paiement.php
<?php

namespace App\Entity;

use App\Repository\PaiementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PaiementRepository::class)
 */
class Paiement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Inscription::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $inscription;

    /**
     * @ORM\ManyToOne(targetEntity=Frais::class)
     */
    private $frais;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $montant_paye;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $montant_reste;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $creted_by;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_active;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInscription(): ?Inscription
    {
        return $this->inscription;
    }

    public function setInscription(?Inscription $inscription): self
    {
        $this->inscription = $inscription;

        return $this;
    }

    public function getFrais(): ?Frais
    {
        return $this->frais;
    }

    public function setFrais(?Frais $frais): self
    {
        $this->frais = $frais;

        return $this;
    }

    public function getMontantPaye(): ?float
    {
        return $this->montant_paye;
    }

    public function setMontantPaye(?float $montant_paye): self
    {
        $this->montant_paye = $montant_paye;

        return $this;
    }

    public function getMontantReste(): ?float
    {
        return $this->montant_reste;
    }

    public function setMontantReste(?float $montant_reste): self
    {
        $this->montant_reste = $montant_reste;

        return $this;
    }

    public function getCretedBy(): ?User
    {
        return $this->creted_by;
    }

    public function setCretedBy(?User $creted_by): self
    {
        $this->creted_by = $creted_by;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }



}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $nom_complet;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNomComplet(): ?string
    {
        return $this->nom_complet;
    }

    public function setNomComplet(?string $nom_complet): self
    {
        $this->nom_complet = $nom_complet;

        return $this;
    }
}

src/Controller/PaiementController.php
<?php

namespace App\Controller;

use App\Entity\Classe;
use App\Entity\Frais;
use App\Entity\Inscription;
use App\Entity\Paiement;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;

class PaiementController extends AbstractController
{
    /**
     * @Route("/payement/{inscription}", name="paiement")
     * @param $inscription
     * @return Response
     */
    public function index($inscription, Request $request, EntityManagerInterface $entityManager): Response
    {
        $eleve = $this->getDoctrine()->getRepository(Inscription::class)
            ->findOneBy(['token'=>$inscription], []);
        if ($request->isMethod('POST'))
        {
            $data = $request->request->all();
            if($this->isCsrfTokenValid('paiement', $data['_token']))
            {
                $paiement = new Paiement();
                $paiement->setMontantPaye($data['montant_paye']);
                $paiement->setMontantReste($data['montant_reste']);
                $paiement->setFrais($this->getDoctrine()->getRepository(Frais::class)
                    ->find($data['frais']));
                $paiement->setInscription($eleve);
                $paiement->setToken($data['_token']);
                $paiement->setIsActive(true);
                $paiement->setCreatedAt(new \DateTime('now'));
                $entityManager->persist($paiement);
                $entityManager->flush();
            }
        }
        $frais_non_regles = $this->getDoctrine()->getRepository(Paiement::class)
            ->NonRegles($inscription);
        $frais_regles = $this->getDoctrine()->getRepository(Paiement::class)
            ->findFraisRegles($inscription);
        return $this->render('paiement/index.html.twig', [
            'controller_name' => 'PaiementController',
            'ordre'=>$frais_regles,
            'frais'=>$frais_non_regles,
            'eleve'=>$eleve
        ]);
    }

    /**
     * @param $token
     * @param $inscription
     * @param EntityManagerInterface $entityManager
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("ajouter_partie/{token}/{inscription}/{new_token}", name="ajouter_partie")
     */
    public function ajouter_partie($token, $inscription, $new_token, EntityManagerInterface $entityManager, Request $request)
    {
        $paiement = $this->getDoctrine()->getRepository(Paiement::class)
            ->findOneBy(['token'=>$token], []);
        $inscript = $this->getDoctrine()->getRepository(Inscription::class)
            ->findOneBy(['token'=>$inscription], []);
        $partie = new Paiement();
        $partie->setCreatedAt(new \DateTime('now'));
        $partie->setIsActive(true);
        $partie->setInscription($inscript);
        $partie->setCretedBy($this->getUser());
        $partie->setMontantPaye($paiement->getMontantReste());
        $partie->setMontantReste(0);
        $partie->setFrais($paiement->getFrais());
        $partie->setToken($new_token);

        //dd($partie);
        $entityManager->persist($partie);
        $entityManager->flush();
        return $this->redirectToRoute('paiement', ['inscription'=>$inscription]);
    }

    /**
     * @Route("eleves_en_ordre", name="eleves_en_ordre")
     */
    public function afficher_eleves()
    {
        $liste_frais = $this->getDoctrine()->getRepository(Frais::class)
            ->findBy(['is_active'=>true]);
        $liste_classes = $this->getDoctrine()->getRepository(Classe::class)
            ->findBy(['is_active'=>true]);
        $paiements = $this->getDoctrine()->getRepository(Paiement::class)
            ->findBy(['is_active'=>true]);
        return $this->render('paiement/eleves_en_ordre.html.twig', [
            'liste_frais'=>$liste_frais,
            'liste_classes'=>$liste_classes,
            'paiements'=>$paiements
        ]);
    }

    /**
     * @Route("trier_eleves", name="trier_eleves")
     *
     */
    public function trier_eleves(Request $request)
    {
        if($request->isXmlHttpRequest()){
            $data = $request->request->all();
            $frais = $data['frais'];
            $classe = $data['classe'];

            $eleves = $this->getDoctrine()->getRepository(Paiement::class)
                ->findElevesOrdreFrais($frais, $classe);
//            dd($eleves);
            return new JsonResponse($eleves);
        }
    }

    /**
     * @Route("historique_paiement", name="historique_paiement")
     */
    public function historique_paiement(Request $request)
    {
        $liste_classes = $this->getDoctrine()->getRepository(Classe::class)
            ->findBy(['is_active'=>true]);
        $liste_frais = $this->getDoctrine()->getRepository(Frais::class)
            ->findBy(['is_active'=>true]);
        $historique = $this->getDoctrine()->getRepository(Paiement::class)
            ->findHistoriquePaiements();
        if($request->isXmlHttpRequest())
        {
            $data = $request->request->all();
            $paiement = $this->getDoctrine()->getRepository(Paiement::class)
                ->findHistoriquePaiement($data['date']);
            return new JsonResponse($paiement);
        }

        return $this->render('paiement/historique_paiement.html.twig', [
            'liste_classes'=>$liste_classes,
            'liste_frais'=>$liste_frais,
            'paiements'=>$historique
        ]);
    }

    /**
     * @Route("facture_mono_frais/{token}", name="facture_mono_frais")
     */
    public function facturer_mono_frais($token, EntityManagerInterface $entityManager)
    {
        $paiement = $this->getDoctrine()->getRepository(Paiement::class)
            ->findOneByToken(['token', $token], []);
        return $this->render('paiement/facture_mono_frais.html.twig', [
            'paiement'=>$paiement
        ]);
    }


}

templates/paiement/eleves_en_ordre.html.twig
{% include 'extension/sidebar.html.twig' %}
<!-- Header -->
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <h6 class="h2 text-white d-inline-block mb-0">Default</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#">Accueil</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Liste d'eleves en ordre</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- Card stats -->
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Elèves en ordre</h3>
                        </div>
                        <div class="col text-right">
                            <select name="classe" id="classe" class="form-control">
                                <option selected="selected">Choisir une classe...</option>>
                                {% for classe in liste_classes %}
                                    <option value="{{ classe.id }}">{{ classe.designation~' '~classe.options.designation }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col">
                            <select name="frais" id="frais" class="form-control">
                                <option selected="selected">Choisir un frais...</option>>
                                {% for frais in liste_frais %}
                                    <option value="{{ frais.id }}">{{ frais.designation }}</option>
                                {% endfor %}
                            </select>
                        </div>
                            <input type="button" class="btn btn-primary" name="recherche" id="recherche" value="RECHERCHER">
                    </div>
                </div>
                <div class="table-responsive" id="tableau">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nom complet</th>
                            <th scope="col">Classe</th>
                            <th scope="col">Frais</th>
                            <th scope="col">M. Fixe</th>
                            <th scope="col">M. Payé</th>
                            <th scope="col">M. Resté</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody id="tbody">
                        {% set i = 1 %}
                        {% for paiement in paiements %}
                            <tr>
                                <td>
                                    {{ i }}
                                </td>
                                <td>
                                    {{ paiement.inscription.eleve.nomComplet|upper }}
                                </td>
                                <td>
                                    {{ paiement.inscription.classe.designation~' '~paiement.inscription.classe.options.designation }}
                                </td>
                                <td>
                                    {{ paiement.frais.designation }}
                                </td>
                                <td>
                                    {{ paiement.frais.montant }}
                                </td>
                                <td>
                                    {{ paiement.montantPaye }}
                                </td>
                                <td>
                                    {{ paiement.montantReste }}
                                </td>
                                <td>
                                    <a href="">Facturer</a>
                                </td>
                            </tr>
                            {% set i = i + 1 %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% include "extension/footer.html.twig" %}
</div>
{% block javascripts %}
     <script src="{{ asset('my_js/paiement_frais_par_classe.js') }}"></script>
{% endblock %}

templates/paiement/facture_mono_frais.html.twig
{% include 'extension/sidebar.html.twig' %}
<!-- Header -->
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <h6 class="h2 text-white d-inline-block mb-0">Default</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#">Accueil</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Inscription</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- Card stats -->
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col text-right">
                            <button href="#!" class="btn btn-sm btn-primary" onclick="HTMLtoPDF()">Generer PDF</button>
                        </div>
                    </div>
                </div>
                <div class="table-responsive" id="HTMLtoPDF">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <img src="{{ asset('assets/img/logo_insoft.png') }}" alt="Logo" class="img-responsive h-50 w-25">
                                <h3>PROVINCE DU LUALABA</h3>
                                <h3>VILLE DE KOLWEZI</h3>
                                <h3>COMPLEXE SCOLAIRE INSOFTWARE</h3>
                            </div>
                            <div class="col">

                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <h2 class="text-center">Facture N° 0{{ paiement.id }}</h2>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <h3>Eleve :</h3>
                                <span>{{ paiement.inscription.eleve.nomComplet|upper }}, {{ paiement.inscription.classe.designation~' '~paiement.inscription.classe.options.designation }}</span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <table>
                                    <thead>
                                        <th>Designation</th>
                                        <th>Montant</th>
                                        <th>M. Payé</th>
                                        <th>M. Resté</th>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ paiement.designation }}</td>
                                            <td>{{ paiement.montant }}</td>
                                            <td>{{ paiement.montant_paye }}</td>
                                            <td>{{ paiement.montant_reste }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                SIGNATURE
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
    {% include "extension/footer.html.twig" %}
</div>
{% block javascripts %}
    <script src="{{ asset('my_js/paiement_frais_par_classe.js') }}"></script>
{% endblock %}

templates/paiement/index.html.twig
{% include 'extension/sidebar.html.twig' %}
<!-- Header -->
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <h6 class="h2 text-white d-inline-block mb-0">Default</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#">Accueil</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Inscription</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!-- Card stats -->
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="mb-0">Elève : {{ eleve.eleve.nomComplet|upper ~', '~eleve.classe.designation ~' '~eleve.classe.options.designation }}</h3>
                        </div>
                        <div class="col text-right">
                            <a href="#!" class="btn btn-sm btn-primary">See all</a>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <form method="post">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <select name="frais" id="frais" class="form-control form-control-sm">
                                            {% for frais in frais %}
                                                <option label="{{frais.designation~' '~frais.montant }}" value="{{ frais.id }}">{{ frais.montant }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <input type="hidden" name="_token" value="{{ csrf_token('paiement') }}">
                                        <input type="text" class="form-control form-control-sm" name="montant_paye" id="montant_paye" placeholder="Montant payé">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <input type="hidden" class="form-control form-control-sm" id="montant_reste" name="montant_reste" placeholder="Montant resté">
                                        <input type="text" class="form-control form-control-sm" id="reste" name="reste" placeholder="Montant resté" disabled>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <input type="submit" class="btn btn-primary btn-sm" value="ENREGISTRER">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <h3>Frais payés</h3>
                                <table class="table align-items-center table-flush">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">#</th>
                                        <th>Date</th>
                                        <th scope="col">Désignation</th>
                                        <th scope="col">Montant</th>
                                        <th scope="col">M. Payé</th>
                                        <th scope="col">M. Resté</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% set i = 1 %}
                                    {% for frais in ordre %}
                                        <tr>
                                        <td>
                                            {{ i }}
                                        </td>
                                        <td>
                                            {{ frais.created_at|date('d/m/Y') }}
                                        </td>
                                        <td>
                                            {{ frais.designation|upper }}
                                        </td>
                                        <td>
                                            {{ frais.montant }}
                                        </td>
                                        <td>
                                            {{ frais.montant_paye }}
                                        </td>
                                        <td>
                                            {{ frais.montant_reste }}
                                        </td>
                                        <td>
                                            <a href="{{ path('facture_mono_frais', {'token': frais.token}) }}">Facturer</a>
                                            {% if frais.montant_reste > 0 %}
                                                <a href="{{ path('ajouter_partie', {'token': frais.token, 'inscription': eleve.token, 'new_token': csrf_token('new_token')}) }}">Ajouter</a>
                                            {% endif %}

                                        </td>
                                    </tr>
                                        {% set i = i + i %}
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="col">
                                Frais non payés
                                <table class="table align-items-center table-flush">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Désignation</th>
                                        <th scope="col">Montant</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% set i = 1 %}
                                    {% for frais in frais %}
                                        <tr>
                                            <td>
                                                {{ i }}
                                            </td>
                                            <td>
                                                {{ frais.designation|upper }}
                                            </td>
                                            <td>
                                                {{ frais.montant }}
                                            </td>
                                            <td>
                                                <a href="">Payer</a>
                                            </td>
                                        </tr>
                                    {% set i = i+1 %}
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
    {% include "extension/footer.html.twig" %}
</div>
<script>
    $(document).ready(function(){
        $("#montant_paye").on("keyup", function(){
            let paye = $(this).val()
            let montant = $("#frais").val()
            let option = $("#frais").find("option[value="+montant+"]").text()

            if(isNaN(paye))
            {
                console.log("NaN")
                return false
            }else{
                let reste = option - paye
                console.log(reste)
                $("#montant_reste").val(reste)
                $("#reste").val(reste)
            }
        })
    })
</script>